DandyDeveloper/charts

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/redis-ha-statefulset.yaml

We were encountering multiple warnings like
> 110m        Warning   Unhealthy                      pod/hm-production-redis-server-1                             Liveness probe failed: Get http://10.244.36.168:9121/metrics: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Specifically targeting metrics endpoint. Increasing time timeoutSeconds resolved it.

[chart/redis-ha] Increase timeoutSeconds for exporter

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/redis-ha-pdb.yaml

Signed-off-by: Leo Petrazickis <leons@autonomic.ai>
There's a bug in the PodDisruptionBudget selector that includes pods that shouldn't be in scope.
- fixes #45 

[charts/redis-ha] Fix PDB selector to not match test pods

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/_configs.tpl
charts/redis-ha/templates/redis-ha-statefulset.yaml

Looks like using `timeout` in a process within the Redis containers isn't killing or doing anything with it. I also don't see a need for the timeout because the liveness already has this in place. 
Removing entirely. As well as adding small logic to remove TLS params when TLS disabled. 
- fixes #76

[charts/redis-ha] Removing timeout from liveness shell process.

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/redis-ha-configmap.yaml

The current chart fails with haproxy 2.3.2 with following error:
```[NOTICE] 001/071757 (1) : haproxy version is 2.3.2-d522db7
[NOTICE] 001/071757 (1) : path to executable is /usr/local/sbin/haproxy
[ALERT] 001/071757 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:82]: Missing LF on last line, file might have been truncated at position 68.
[ALERT] 001/071757 (1) : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg
[ALERT] 001/071757 (1) : Fatal errors found in configuration.
```
This patch fixes the issue

Newer versions of haproxy expect LF on config last line

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/redis-ha-statefulset.yaml
charts/redis-ha/values.yaml

For large redis instances (50GB for instance) and slow disks, writing RDB snapshot to disks may require more time (even 5 minutes), and terminationGracePeriodSeconds should be configurable.

Add option to change terminationGracePeriodSeconds

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/_configs.tpl
charts/redis-ha/templates/redis-ha-health-configmap.yaml
charts/redis-ha/templates/redis-ha-statefulset.yaml

With recent changes to redis_liveness.sh, the POD (wrongly) will be marked as ready when a sync is in progress.
I've added an new redis_readiness.sh.

Add separate redis_readiness check

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/_configs.tpl
charts/redis-ha/templates/redis-ha-statefulset.yaml
charts/redis-ha/templates/redis-haproxy-deployment.yaml

- Adds handling of Sentinel auth in HAProxy, 
- Handles ONLY Sentinel auth being set
- Uses env vars in HAProxy config to avoid/fix escaping issues in Redis and Sentinel passwords
- fixes #133

Handle Sentinel auth, use env vars in HAProxy config

---

charts/redis-ha/Chart.yaml
charts/redis-ha/README.md
charts/redis-ha/templates/redis-auth-secret.yaml
charts/redis-ha/templates/redis-ha-announce-service.yaml
charts/redis-ha/templates/redis-ha-configmap.yaml
charts/redis-ha/templates/redis-ha-exporter-script-configmap.yaml
charts/redis-ha/templates/redis-ha-health-configmap.yaml
charts/redis-ha/templates/redis-ha-pdb.yaml
charts/redis-ha/templates/redis-ha-psp.yaml
charts/redis-ha/templates/redis-ha-role.yaml
charts/redis-ha/templates/redis-ha-rolebinding.yaml
charts/redis-ha/templates/redis-ha-secret.yaml
charts/redis-ha/templates/redis-ha-service.yaml
charts/redis-ha/templates/redis-ha-serviceaccount.yaml
charts/redis-ha/templates/redis-ha-servicemonitor.yaml
charts/redis-ha/templates/redis-ha-statefulset.yaml
charts/redis-ha/templates/redis-haproxy-deployment.yaml
charts/redis-ha/templates/redis-haproxy-pdb.yaml
charts/redis-ha/templates/redis-haproxy-psp.yaml
charts/redis-ha/templates/redis-haproxy-role.yaml
charts/redis-ha/templates/redis-haproxy-rolebinding.yaml
charts/redis-ha/templates/redis-haproxy-service.yaml
charts/redis-ha/templates/redis-haproxy-serviceaccount.yaml
charts/redis-ha/templates/redis-haproxy-servicemonitor.yaml
charts/redis-ha/templates/redis-tls-secret.yaml
charts/redis-ha/templates/sentinel-auth-secret.yaml
charts/redis-ha/values.yaml

Consumers may have a requirement to have governance labels applied to all (or a subset of) resources. Currently the consumer has the option to specify some labels, but instead of playing whack-a-mole it may be easier to have a key for labels that will be applied to all resources.
- fixes #142 
Let me know if a different key to `additionalLabels` is required. 

[charts/redis-ha] Add additional labels

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/redis-ha-network-policy.yaml

Allows connectivity from HAProxy pods to redis pods on 26379 6379 tcp when HAProxy is enabled
#155 
- [/ ] Chart Version bumped
- [/ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

[stable/redis-ha] Update network policy to allow HAProxy connectivity when enabled

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/redis-ha-servicemonitor.yaml
charts/redis-ha/templates/redis-haproxy-servicemonitor.yaml

The labels for service monitors (redis+haproxy) are not working as expected. There are global missing labels and helm fails when service monitor labels are provided along with extraLabels.
Helm template output for current version shows the extra label key outside of labels and duplicated namespace, this fails the deploy:
```sh
→ helm template . \
--set=replicas=1 \
--set=exporter.enabled=true \
--set=exporter.serviceMonitor.enabled=true \
--set=extraLabels.extralabel-key=extralabel-value \
--set=exporter.serviceMonitor.labels.svcmon-key=svcmon-value \
--set=exporter.serviceMonitor.namespace=monitor-namespace \
--api-versions=monitoring.coreos.com/v1
[...]
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
labels:
svcmon-key: svcmon-value
name: RELEASE-NAME-redis-ha …
```

[stable/redis-ha] Fix service-monitor labels

---

charts/redis-ha/README.md

Add the splitBrainDetection resources field. This is a mandatory field. I did an update from the 4.5.7 version to 4.14.9 and it complained for missing resources on the split brain detection container and it worked after I added it.
It shows in the README file that the resource field of the splitBrainDetection is needed.

[redis-ha] Update README.md

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/_configs.tpl

Instead of listening only on IPv4, this updates the configuration to
start an IPv6 socket that also accepts connections over IPv4 using the
v4v6 flag from
http://cbonte.github.io/haproxy-dconv/2.5/configuration.html#5.1-v4v6
This allows clusters that are in IPv6 only mode (for example, an EKS
cluster) to bring up an HA redis correctly.
- fixes #98 
This requires that we bind to `[::]` with the `v4v6` flag which will create a socket that can accept both IPv4 and IPv6. The other solution is to explicitly bind to both by adding two `bind` statements instead.
Without this change the HA Proxy systems would continue to fail over and over.

[charts/redis-ha] Deploy HAProxy config in IPv4/IPv6 mode

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/redis-ha-statefulset.yaml

Add "config-sentinel.conf" to checksum/init-config annotation so that changes to the sentinel.conf trigger a restart of the Redis pods
- fixes #147 

[stable/redia-ha] Update redis-ha-statefulset.yaml

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/_helpers.tpl
charts/redis-ha/templates/redis-ha-pdb.yaml
charts/redis-ha/templates/redis-haproxy-pdb.yaml

Signed-off-by: Mikhail Konyakhin <m.konyahin@gmail.com>
Use correct API version of PodDisruptionBudget for k8s equal or above 1.21.0
- fixes #187 
N/A

[charts/redis-ha] Use correct API version of PodDisruptionBudget. (#187)

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/_configs.tpl

Root problem: Some times separate redis-ha installations hijack slaves from each-other. This occurs when a slave is registered by *pod* ip, not service-ip. And since pod ips are not fixed, the IP may be assigned to another (unfortunately redis) pod ....
A sample `config-init` container log for a bad pod, is as follows: (service cidr is 10.43.0.0/16, pod cidr is 10.42.0.0/16)
```
Mon May 30 05:25:09 UTC 2022..
Could not connect to Redis at myredis:26379: Try again
Could not connect to Redis at myredis:26379: Try again
Could not connect to Redis at myredis:26379: Try again
Mon May 30 05:25:54 UTC 2022 Did not find redis master ()
Identify announce ip for this pod..
using (myredis-announce-0) or (myredis-server-0)
identified announce (10.42.12.41)
Setting up defaults..
```

[stable/redis-ha] Fix using pod ip instead of service for announce-ip

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/_configs.tpl

Signed-off-by: Aaron Layfield <aaron.layfield@gmail.com>
Fixes the operand in the split brain script that should be POSIX, not bash.
- fixes #229

[redis-ha] Fixing POSIX operand, we don't use bash.

---

charts/redis-ha/Chart.yaml
charts/redis-ha/values.yaml

Signed-off-by: Justin Marquis <34fathombelow@protonmail.com>
Upgrade Redis to 7.0.5 to avoid CVE-2022-35951
Refer to [GHSA-5gc4-76rx-22c9](https://github.com/redis/redis/security/advisories/GHSA-5gc4-76rx-22c9) for more details.

[charts/redis-ha] Upgrade Redis to 7.0.5 avoid CVE-2022-35951

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/redis-ha-statefulset.yaml

It adds securityContext to the redis-exporter container in redis-ha-sts
Same securityContext as in other containers
Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>

[stable/redis-ha] add containerSecurityContext to redis-exporter container

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/redis-haproxy-deployment.yaml
charts/redis-ha/values.yaml

Where this label come from: DandyDeveloper/charts#6
This label causes two main problems for us:
- `helm-diff` plugin is not working correctly
- all changes on a chart that uses redis-ha as dependency triggers a redeployment of HAproxy pods.
If we reduce number of replicas to 2 in HAproxy we can allow clusters of 3 nodes upgrade without having any of this issues.
Another option in that case can be just to disable `hardAntiAffinity`.
- fixes #189

[charts/redis-ha] Remove HAproxy revision label

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/redis-ha-announce-service.yaml

The annotation `service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"` is deprecated since Kubernetes 1.11, following https://github.com/kubernetes/kubernetes/pull/63742 The template input both fields, the annotation and the substituted field `.spec.publishNotReadyAddresses=True` but it becomes incompatible with Kubernetes <=1.10 so a check Kubernetes version resolve it put the right fields based on Kubernetes version.
- fixes #

fix: publishNotReadyAddresses K8s version check

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/_configs.tpl

When you run Redis with TLS with `authClients` set to "no", the fix-split-brain sidecar does not talk to Redis or Sentinel over TLS. 
`authClients` _only_ configures whether or not mutual TLS is required therefore moving the `--tls --cacert` arguments out of the conditional checking `authClients` fixes this issue.
Also updated the `TLS_CLIENT_OPTION` so that `--cert` and `--key` are only used if client authentication is required. 
<details>
<summary>Example Helm values snippet</summary>
```yaml
redis:
port: 0
tlsPort: 6385
tlsReplication: true
authClients: "no"
sentinel:
port: 0
tlsPort: 26385
tlsReplication: true
authClients: "no"
tls:
secretName: cert-redis
certFile: tls.crt
keyFile: tls.key
caCertFile: ca.crt
```
</details>
Didn't raise an issue, though I can if it helps.
[Place an …

[charts/redis-ha] Fix redis-cli --tls argument usage

---

charts/redis-ha/templates/NOTES.txt

this pr will fix deprecation warnings in `kubectl` commands and also specifying container name in `exec` command

[stable/redis-ha] 🐛 fix: better kubectl commands in NOTES

---

.github/workflows/publish.yml

Looks like publishing the latest version of the chart failed. Not sure if it was related to checking out `actions/checkout@v2` but it could use the updating. That's when I also noticed the helm chart releaser was archived and so I switched to the more official recommended solution.

Update GHA to use updated versions and non-deprecated publisher

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/_configs.tpl

When
-  A restart occurs for a redis pod
-  Some modification (like resource increase) occurs 
-  draining a node
The command fix-split-brain.sh container will not gracefully exit and goes into an infinite loop and will not be stopped until terminationGracePeriodSeconds timeouts. In this commit a TERM signal trap is added to prevent such a infinite loop and gracefully exit fix-split-brain.sh

[dandydev/redis-ha] Add TERM signal trap to Redis-ha fix-split-brain.sh to prevent infinite loop and gracefully exit

---

charts/redis-ha/Chart.yaml
charts/redis-ha/README.md
charts/redis-ha/templates/redis-ha-statefulset.yaml
charts/redis-ha/templates/redis-haproxy-deployment.yaml
charts/redis-ha/values.yaml

Context is this feature request over there:
- https://github.com/argoproj/argo-helm/issues/2704
`.Values.global.xyz` is a reserved section which is passed to all dependency charts inside a helm chart (also called subcharts).
Implementing this is useful for both
- direct deployment of this helm chart
- use `redis-ha` as a dependency chart (like we do in argoproj/argo-helm)
Partially this one over there:
- https://github.com/argoproj/argo-helm/issues/2704
Other well-known charts implementing this:
- [grafana/loki](https://github.com/grafana/loki)
- [grafana/helm-charts](https://github.com/grafana/helm-charts)
- [dapr/dapr](https://github.com/dapr/dapr)
- [argoproj/argo-helm](https://github.com/argoproj/argo-helm)
- [istio/istio](https://github.com/istio/istio)
- ...?
[Place an '[x]' (no …

feat: Add ability to define priorityClassName globally

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/redis-ha-statefulset.yaml

`global.priorityClassName` or `priorityClassName` will cause an error in the output of Redis-ha's StatefulSet.

[chart/redis-ha] redis-ha-statefulset: bugfix StatefulSet priorityClassName

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/_configs.tpl

The `${response:0:7}` syntax is non-POSIX and not understood by Debian's dash shell, so if a Debian-based Redis image is used the liveness check breaks on slaves. A case statement makes this check more legible anyway, in my opinion, and works in all the POSIX-compatible shells (busybox ash, dash, and bash).
No issue created (yet).
- (n/a) Variables are documented in the README.md

redis-ha: fix busybox-ash-ism in redis_liveness.sh

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/redis-ha-network-policy.yaml
charts/redis-ha/values.yaml

- In some situations (GKE cluster with [Cloud DNS](https://cloud.google.com/kubernetes-engine/docs/how-to/cloud-dns#architecture)), the DNS server is configured on the local network IP range (169.254.0.0/16), so we should allow this CIDR in the default network policy.

[stable/redis-ha]: Allow DNS requests to local network

---

charts/redis-ha/Chart.yaml
charts/redis-ha/README.md
charts/redis-ha/values.yaml

Adds some missing bits from the `values.yaml` for documentation purposes. 
- fixes #282

Adding nameOverride & fullNameOverride

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/redis-haproxy-deployment.yaml

Adding port 8888 to the HA Proxy deployment manifest. 
- fixes #276

Adding port 8888 to Deployment

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/redis-ha-statefulset.yaml
charts/redis-ha/values.yaml

This PR adds support for using a remote Redis instance as a data source for restoration. It utilizes the `redis-cli --rdb` command to perform the restore operation.

[stable/redis-ha]: add redis source to restore options

---

charts/redis-ha/Chart.yaml
charts/redis-ha/values.yaml

- Updates HAProxy to 3.0.x, which is the latest version of the current LTS branch (2.9 was not and will be EOL 2025-Q1; see https://haproxy.org/)
- Updates redis_exporter to the latest version; also, the author now publishes official images to quay.io in addition to Docker Hub (see https://github.com/oliver006/redis_exporter/issues/537)
- fixes #

redis-ha: minor updates to haproxy and redis_exporter versions

---

charts/redis-ha/Chart.yaml
charts/redis-ha/README.md
charts/redis-ha/templates/_configs.tpl
charts/redis-ha/values.yaml

This fixes the issue that I'm unable to deploy the helm chart on arm64 nodes. This is due to v0.5.0 does not support arm64
https://hub.docker.com/r/koalaman/shellcheck/tags
After bumping just the shellcheck version I got this new error:
```
In /readonly-config/init.sh line 239:
"Error: Could not resolve the announce ip for this pod."
^-- SC2288 (warning): This is interpreted as a command name ending with '.'. Double check syntax.
For more information:
https://www.shellcheck.net/wiki/SC2288 -- This is interpreted as a command ...
stream closed EOF for argocd/argocd-redis-ha-configmap-test (check-init)
```
So I just removed that dot.

[stable/redis-ha] Bump shellcheck in order to fix arm64 deployment

---

charts/redis-ha/Chart.yaml
charts/redis-ha/README.md
charts/redis-ha/values.yaml

fixes uneffective value "fullNameOverride" in redis-ha chart, which is spelled differently in helpers.tpl file
- fixes #325

[stable/redis-ha] renamed redis-ha value "fullNameOverride" to "fullnameOverride" 

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/redis-ha-pdb.yaml
charts/redis-ha/templates/redis-ha-statefulset.yaml

Fixes the following message on GKE:
> StatefulSet doesn't have a Pod Disruption Budget. This means that all Pods in the StatefulSet might experience simultaneous disruption during scenarios like node upgrades
- fixes #307

fix(redis-ha): match pdb selectors with sts selectors

---

charts/redis-ha/Chart.yaml
charts/redis-ha/templates/tests/test-redis-ha-pod.yaml

Allows setting pod annotations on the test pod.
https://github.com/DandyDeveloper/charts/issues/304

[stable/redis-ha]: support pod annotations on the test-ha pod
